"""Generated RoboTwin task mapping entries."""

from .robotwin_adjust_bottle_001_bottle.config import TaskConfig as RobotwinAdjustBottle001BottleConfig
from .robotwin_adjust_bottle_001_bottle_base0.config import TaskConfig as RobotwinAdjustBottle001BottleBase0Config
from .robotwin_adjust_bottle_001_bottle_base10.config import TaskConfig as RobotwinAdjustBottle001BottleBase10Config
from .robotwin_adjust_bottle_001_bottle_base11.config import TaskConfig as RobotwinAdjustBottle001BottleBase11Config
from .robotwin_adjust_bottle_001_bottle_base13.config import TaskConfig as RobotwinAdjustBottle001BottleBase13Config
from .robotwin_beat_block_hammer_020_hammer.config import TaskConfig as RobotwinBeatBlockHammer020HammerConfig
from .robotwin_blocks_ranking_rgb_box_demo.config import TaskConfig as RobotwinBlocksRankingRgbBoxDemoConfig
from .robotwin_blocks_ranking_size_box_demo.config import TaskConfig as RobotwinBlocksRankingSizeBoxDemoConfig
from .robotwin_click_alarmclock_046_alarm_clock_base1.config import TaskConfig as RobotwinClickAlarmclock046AlarmClockBase1Config
from .robotwin_click_alarmclock_046_alarm_clock_base2.config import TaskConfig as RobotwinClickAlarmclock046AlarmClockBase2Config
from .robotwin_click_alarmclock_046_alarm_clock_base3.config import TaskConfig as RobotwinClickAlarmclock046AlarmClockBase3Config
from .robotwin_click_alarmclock_046_alarm_clock_base4.config import TaskConfig as RobotwinClickAlarmclock046AlarmClockBase4Config
from .robotwin_click_bell_050_bell_base0.config import TaskConfig as RobotwinClickBell050BellBase0Config
from .robotwin_click_bell_050_bell_base1.config import TaskConfig as RobotwinClickBell050BellBase1Config
from .robotwin_dump_bin_bigbin_011_dustbin.config import TaskConfig as RobotwinDumpBinBigbin011DustbinConfig
from .robotwin_dump_bin_bigbin_011_dustbin_base0.config import TaskConfig as RobotwinDumpBinBigbin011DustbinBase0Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base0.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase0Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base1.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase1Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base10.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase10Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base2.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase2Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base3.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase3Config
from .robotwin_dump_bin_bigbin_063_tabletrashbin_base4.config import TaskConfig as RobotwinDumpBinBigbin063TabletrashbinBase4Config
from .robotwin_grab_roller_102_roller_base1.config import TaskConfig as RobotwinGrabRoller102RollerBase1Config
from .robotwin_grab_roller_102_roller_base2.config import TaskConfig as RobotwinGrabRoller102RollerBase2Config
from .robotwin_hanging_mug_039_mug_base0.config import TaskConfig as RobotwinHangingMug039MugBase0Config
from .robotwin_hanging_mug_039_mug_base1.config import TaskConfig as RobotwinHangingMug039MugBase1Config
from .robotwin_hanging_mug_039_mug_base10.config import TaskConfig as RobotwinHangingMug039MugBase10Config
from .robotwin_hanging_mug_039_mug_base11.config import TaskConfig as RobotwinHangingMug039MugBase11Config
from .robotwin_hanging_mug_039_mug_base12.config import TaskConfig as RobotwinHangingMug039MugBase12Config
from .robotwin_hanging_mug_039_mug_base2.config import TaskConfig as RobotwinHangingMug039MugBase2Config
from .robotwin_hanging_mug_039_mug_base3.config import TaskConfig as RobotwinHangingMug039MugBase3Config
from .robotwin_hanging_mug_039_mug_base4.config import TaskConfig as RobotwinHangingMug039MugBase4Config
from .robotwin_lift_pot_060_kitchenpot_base0.config import TaskConfig as RobotwinLiftPot060KitchenpotBase0Config
from .robotwin_lift_pot_060_kitchenpot_base1.config import TaskConfig as RobotwinLiftPot060KitchenpotBase1Config
from .robotwin_lift_pot_060_kitchenpot_base2.config import TaskConfig as RobotwinLiftPot060KitchenpotBase2Config
from .robotwin_lift_pot_060_kitchenpot_base3.config import TaskConfig as RobotwinLiftPot060KitchenpotBase3Config
from .robotwin_lift_pot_060_kitchenpot_base4.config import TaskConfig as RobotwinLiftPot060KitchenpotBase4Config
from .robotwin_lift_pot_060_kitchenpot_base5.config import TaskConfig as RobotwinLiftPot060KitchenpotBase5Config
from .robotwin_lift_pot_060_kitchenpot_base6.config import TaskConfig as RobotwinLiftPot060KitchenpotBase6Config
from .robotwin_lift_pot_060_kitchenpot_base7.config import TaskConfig as RobotwinLiftPot060KitchenpotBase7Config
from .robotwin_move_can_pot_060_kitchenpot_base0.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase0Config
from .robotwin_move_can_pot_060_kitchenpot_base1.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase1Config
from .robotwin_move_can_pot_060_kitchenpot_base2.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase2Config
from .robotwin_move_can_pot_060_kitchenpot_base3.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase3Config
from .robotwin_move_can_pot_060_kitchenpot_base4.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase4Config
from .robotwin_move_can_pot_060_kitchenpot_base5.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase5Config
from .robotwin_move_can_pot_060_kitchenpot_base6.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase6Config
from .robotwin_move_can_pot_060_kitchenpot_base7.config import TaskConfig as RobotwinMoveCanPot060KitchenpotBase7Config
from .robotwin_move_pillbottle_pad_080_pillbottle_base1.config import TaskConfig as RobotwinMovePillbottlePad080PillbottleBase1Config
from .robotwin_move_pillbottle_pad_080_pillbottle_base4.config import TaskConfig as RobotwinMovePillbottlePad080PillbottleBase4Config
from .robotwin_move_pillbottle_pad_080_pillbottle_base5.config import TaskConfig as RobotwinMovePillbottlePad080PillbottleBase5Config
from .robotwin_move_playingcard_away_081_playingcards_base0.config import TaskConfig as RobotwinMovePlayingcardAway081PlayingcardsBase0Config
from .robotwin_move_playingcard_away_081_playingcards_base1.config import TaskConfig as RobotwinMovePlayingcardAway081PlayingcardsBase1Config
from .robotwin_move_playingcard_away_081_playingcards_base2.config import TaskConfig as RobotwinMovePlayingcardAway081PlayingcardsBase2Config
from .robotwin_move_stapler_pad_048_stapler_base0.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase0Config
from .robotwin_move_stapler_pad_048_stapler_base1.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase1Config
from .robotwin_move_stapler_pad_048_stapler_base2.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase2Config
from .robotwin_move_stapler_pad_048_stapler_base3.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase3Config
from .robotwin_move_stapler_pad_048_stapler_base4.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase4Config
from .robotwin_move_stapler_pad_048_stapler_base5.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase5Config
from .robotwin_move_stapler_pad_048_stapler_base6.config import TaskConfig as RobotwinMoveStaplerPad048StaplerBase6Config
from .robotwin_pick_diverse_bottles_001_bottle.config import TaskConfig as RobotwinPickDiverseBottles001BottleConfig
from .robotwin_pick_diverse_bottles_001_bottle_base0.config import TaskConfig as RobotwinPickDiverseBottles001BottleBase0Config
from .robotwin_pick_diverse_bottles_001_bottle_base10.config import TaskConfig as RobotwinPickDiverseBottles001BottleBase10Config
from .robotwin_pick_diverse_bottles_001_bottle_base11.config import TaskConfig as RobotwinPickDiverseBottles001BottleBase11Config
from .robotwin_pick_diverse_bottles_001_bottle_base13.config import TaskConfig as RobotwinPickDiverseBottles001BottleBase13Config
from .robotwin_pick_dual_bottles_001_bottle.config import TaskConfig as RobotwinPickDualBottles001BottleConfig
from .robotwin_pick_dual_bottles_001_bottle_base0.config import TaskConfig as RobotwinPickDualBottles001BottleBase0Config
from .robotwin_pick_dual_bottles_001_bottle_base10.config import TaskConfig as RobotwinPickDualBottles001BottleBase10Config
from .robotwin_pick_dual_bottles_001_bottle_base11.config import TaskConfig as RobotwinPickDualBottles001BottleBase11Config
from .robotwin_pick_dual_bottles_001_bottle_base13.config import TaskConfig as RobotwinPickDualBottles001BottleBase13Config
from .robotwin_place_a2b_left_047_mouse_base0.config import TaskConfig as RobotwinPlaceA2bLeft047MouseBase0Config
from .robotwin_place_a2b_left_047_mouse_base1.config import TaskConfig as RobotwinPlaceA2bLeft047MouseBase1Config
from .robotwin_place_a2b_left_047_mouse_base2.config import TaskConfig as RobotwinPlaceA2bLeft047MouseBase2Config
from .robotwin_place_a2b_left_048_stapler_base0.config import TaskConfig as RobotwinPlaceA2bLeft048StaplerBase0Config
from .robotwin_place_a2b_left_048_stapler_base1.config import TaskConfig as RobotwinPlaceA2bLeft048StaplerBase1Config
from .robotwin_place_a2b_left_048_stapler_base2.config import TaskConfig as RobotwinPlaceA2bLeft048StaplerBase2Config
from .robotwin_place_a2b_left_048_stapler_base3.config import TaskConfig as RobotwinPlaceA2bLeft048StaplerBase3Config
from .robotwin_place_a2b_left_048_stapler_base4.config import TaskConfig as RobotwinPlaceA2bLeft048StaplerBase4Config
from .robotwin_place_a2b_right_047_mouse_base0.config import TaskConfig as RobotwinPlaceA2bRight047MouseBase0Config
from .robotwin_place_a2b_right_047_mouse_base1.config import TaskConfig as RobotwinPlaceA2bRight047MouseBase1Config
from .robotwin_place_a2b_right_047_mouse_base2.config import TaskConfig as RobotwinPlaceA2bRight047MouseBase2Config
from .robotwin_place_a2b_right_048_stapler_base0.config import TaskConfig as RobotwinPlaceA2bRight048StaplerBase0Config
from .robotwin_place_a2b_right_048_stapler_base1.config import TaskConfig as RobotwinPlaceA2bRight048StaplerBase1Config
from .robotwin_place_a2b_right_048_stapler_base2.config import TaskConfig as RobotwinPlaceA2bRight048StaplerBase2Config
from .robotwin_place_a2b_right_048_stapler_base3.config import TaskConfig as RobotwinPlaceA2bRight048StaplerBase3Config
from .robotwin_place_a2b_right_048_stapler_base4.config import TaskConfig as RobotwinPlaceA2bRight048StaplerBase4Config
from .robotwin_place_bread_basket_075_bread_base0.config import TaskConfig as RobotwinPlaceBreadBasket075BreadBase0Config
from .robotwin_place_bread_basket_075_bread_base1.config import TaskConfig as RobotwinPlaceBreadBasket075BreadBase1Config
from .robotwin_place_bread_basket_075_bread_base2.config import TaskConfig as RobotwinPlaceBreadBasket075BreadBase2Config
from .robotwin_place_bread_basket_076_breadbasket_base0.config import TaskConfig as RobotwinPlaceBreadBasket076BreadbasketBase0Config
from .robotwin_place_bread_basket_076_breadbasket_base1.config import TaskConfig as RobotwinPlaceBreadBasket076BreadbasketBase1Config
from .robotwin_place_bread_basket_076_breadbasket_base2.config import TaskConfig as RobotwinPlaceBreadBasket076BreadbasketBase2Config
from .robotwin_place_bread_basket_076_breadbasket_base3.config import TaskConfig as RobotwinPlaceBreadBasket076BreadbasketBase3Config
from .robotwin_place_bread_basket_076_breadbasket_base4.config import TaskConfig as RobotwinPlaceBreadBasket076BreadbasketBase4Config
from .robotwin_place_bread_skillet_075_bread_base0.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase0Config
from .robotwin_place_bread_skillet_075_bread_base1.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase1Config
from .robotwin_place_bread_skillet_075_bread_base2.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase2Config
from .robotwin_place_bread_skillet_075_bread_base3.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase3Config
from .robotwin_place_bread_skillet_075_bread_base4.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase4Config
from .robotwin_place_bread_skillet_075_bread_base5.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase5Config
from .robotwin_place_bread_skillet_075_bread_base6.config import TaskConfig as RobotwinPlaceBreadSkillet075BreadBase6Config
from .robotwin_place_bread_skillet_106_skillet_base0.config import TaskConfig as RobotwinPlaceBreadSkillet106SkilletBase0Config
from .robotwin_place_burger_fries_006_hamburg.config import TaskConfig as RobotwinPlaceBurgerFries006HamburgConfig
from .robotwin_place_burger_fries_006_hamburg_base0.config import TaskConfig as RobotwinPlaceBurgerFries006HamburgBase0Config
from .robotwin_place_burger_fries_006_hamburg_base1.config import TaskConfig as RobotwinPlaceBurgerFries006HamburgBase1Config
from .robotwin_place_burger_fries_008_tray.config import TaskConfig as RobotwinPlaceBurgerFries008TrayConfig
from .robotwin_place_burger_fries_008_tray_base0.config import TaskConfig as RobotwinPlaceBurgerFries008TrayBase0Config
from .robotwin_place_burger_fries_008_tray_base1.config import TaskConfig as RobotwinPlaceBurgerFries008TrayBase1Config
from .robotwin_place_burger_fries_008_tray_base2.config import TaskConfig as RobotwinPlaceBurgerFries008TrayBase2Config
from .robotwin_place_burger_fries_008_tray_base3.config import TaskConfig as RobotwinPlaceBurgerFries008TrayBase3Config
from .robotwin_place_can_basket_071_can_base0.config import TaskConfig as RobotwinPlaceCanBasket071CanBase0Config
from .robotwin_place_can_basket_071_can_base1.config import TaskConfig as RobotwinPlaceCanBasket071CanBase1Config
from .robotwin_place_can_basket_071_can_base2.config import TaskConfig as RobotwinPlaceCanBasket071CanBase2Config
from .robotwin_place_can_basket_071_can_base3.config import TaskConfig as RobotwinPlaceCanBasket071CanBase3Config
from .robotwin_place_can_basket_110_basket_base0.config import TaskConfig as RobotwinPlaceCanBasket110BasketBase0Config
from .robotwin_place_can_basket_110_basket_base1.config import TaskConfig as RobotwinPlaceCanBasket110BasketBase1Config
from .robotwin_place_can_basket_110_basket_base2.config import TaskConfig as RobotwinPlaceCanBasket110BasketBase2Config
from .robotwin_place_can_basket_110_basket_base3.config import TaskConfig as RobotwinPlaceCanBasket110BasketBase3Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base0.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase0Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base1.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase1Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base10.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase10Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base2.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase2Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base3.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase3Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base4.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase4Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base5.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase5Config
from .robotwin_place_cans_plasticbox_062_plasticbox_base6.config import TaskConfig as RobotwinPlaceCansPlasticbox062PlasticboxBase6Config
from .robotwin_place_container_plate_002_bowl.config import TaskConfig as RobotwinPlaceContainerPlate002BowlConfig
from .robotwin_place_container_plate_002_bowl_base1.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase1Config
from .robotwin_place_container_plate_002_bowl_base2.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase2Config
from .robotwin_place_container_plate_002_bowl_base3.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase3Config
from .robotwin_place_container_plate_002_bowl_base4.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase4Config
from .robotwin_place_container_plate_002_bowl_base5.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase5Config
from .robotwin_place_container_plate_002_bowl_base6.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase6Config
from .robotwin_place_container_plate_002_bowl_base7.config import TaskConfig as RobotwinPlaceContainerPlate002BowlBase7Config
from .robotwin_place_dual_shoes_007_shoe_box.config import TaskConfig as RobotwinPlaceDualShoes007ShoeBoxConfig
from .robotwin_place_dual_shoes_007_shoe_box_base0.config import TaskConfig as RobotwinPlaceDualShoes007ShoeBoxBase0Config
from .robotwin_place_dual_shoes_041_shoe_base0.config import TaskConfig as RobotwinPlaceDualShoes041ShoeBase0Config
from .robotwin_place_dual_shoes_041_shoe_base2.config import TaskConfig as RobotwinPlaceDualShoes041ShoeBase2Config
from .robotwin_place_dual_shoes_041_shoe_base4.config import TaskConfig as RobotwinPlaceDualShoes041ShoeBase4Config
from .robotwin_place_empty_cup_021_cup.config import TaskConfig as RobotwinPlaceEmptyCup021CupConfig
from .robotwin_place_empty_cup_021_cup_base0.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase0Config
from .robotwin_place_empty_cup_021_cup_base1.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase1Config
from .robotwin_place_empty_cup_021_cup_base10.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase10Config
from .robotwin_place_empty_cup_021_cup_base11.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase11Config
from .robotwin_place_empty_cup_021_cup_base12.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase12Config
from .robotwin_place_empty_cup_021_cup_base2.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase2Config
from .robotwin_place_empty_cup_021_cup_base3.config import TaskConfig as RobotwinPlaceEmptyCup021CupBase3Config
from .robotwin_place_fan_box_demo.config import TaskConfig as RobotwinPlaceFanBoxDemoConfig
from .robotwin_place_mouse_pad_047_mouse_base0.config import TaskConfig as RobotwinPlaceMousePad047MouseBase0Config
from .robotwin_place_mouse_pad_047_mouse_base1.config import TaskConfig as RobotwinPlaceMousePad047MouseBase1Config
from .robotwin_place_mouse_pad_047_mouse_base2.config import TaskConfig as RobotwinPlaceMousePad047MouseBase2Config
from .robotwin_place_object_basket_057_toycar_base0.config import TaskConfig as RobotwinPlaceObjectBasket057ToycarBase0Config
from .robotwin_place_object_basket_057_toycar_base1.config import TaskConfig as RobotwinPlaceObjectBasket057ToycarBase1Config
from .robotwin_place_object_basket_057_toycar_base2.config import TaskConfig as RobotwinPlaceObjectBasket057ToycarBase2Config
from .robotwin_place_object_basket_057_toycar_base3.config import TaskConfig as RobotwinPlaceObjectBasket057ToycarBase3Config
from .robotwin_place_object_basket_110_basket_base0.config import TaskConfig as RobotwinPlaceObjectBasket110BasketBase0Config
from .robotwin_place_object_basket_110_basket_base1.config import TaskConfig as RobotwinPlaceObjectBasket110BasketBase1Config
from .robotwin_place_object_basket_110_basket_base2.config import TaskConfig as RobotwinPlaceObjectBasket110BasketBase2Config
from .robotwin_place_object_basket_110_basket_base3.config import TaskConfig as RobotwinPlaceObjectBasket110BasketBase3Config
from .robotwin_place_object_scale_047_mouse_base0.config import TaskConfig as RobotwinPlaceObjectScale047MouseBase0Config
from .robotwin_place_object_scale_047_mouse_base1.config import TaskConfig as RobotwinPlaceObjectScale047MouseBase1Config
from .robotwin_place_object_scale_047_mouse_base2.config import TaskConfig as RobotwinPlaceObjectScale047MouseBase2Config
from .robotwin_place_object_scale_048_stapler_base0.config import TaskConfig as RobotwinPlaceObjectScale048StaplerBase0Config
from .robotwin_place_object_scale_048_stapler_base1.config import TaskConfig as RobotwinPlaceObjectScale048StaplerBase1Config
from .robotwin_place_object_scale_048_stapler_base2.config import TaskConfig as RobotwinPlaceObjectScale048StaplerBase2Config
from .robotwin_place_object_scale_048_stapler_base3.config import TaskConfig as RobotwinPlaceObjectScale048StaplerBase3Config
from .robotwin_place_object_scale_048_stapler_base4.config import TaskConfig as RobotwinPlaceObjectScale048StaplerBase4Config
from .robotwin_place_object_stand_047_mouse_base0.config import TaskConfig as RobotwinPlaceObjectStand047MouseBase0Config
from .robotwin_place_object_stand_047_mouse_base1.config import TaskConfig as RobotwinPlaceObjectStand047MouseBase1Config
from .robotwin_place_object_stand_047_mouse_base2.config import TaskConfig as RobotwinPlaceObjectStand047MouseBase2Config
from .robotwin_place_object_stand_048_stapler_base0.config import TaskConfig as RobotwinPlaceObjectStand048StaplerBase0Config
from .robotwin_place_object_stand_048_stapler_base1.config import TaskConfig as RobotwinPlaceObjectStand048StaplerBase1Config
from .robotwin_place_object_stand_048_stapler_base2.config import TaskConfig as RobotwinPlaceObjectStand048StaplerBase2Config
from .robotwin_place_object_stand_048_stapler_base3.config import TaskConfig as RobotwinPlaceObjectStand048StaplerBase3Config
from .robotwin_place_object_stand_048_stapler_base4.config import TaskConfig as RobotwinPlaceObjectStand048StaplerBase4Config
from .robotwin_place_phone_stand_077_phone_base0.config import TaskConfig as RobotwinPlacePhoneStand077PhoneBase0Config
from .robotwin_place_phone_stand_077_phone_base1.config import TaskConfig as RobotwinPlacePhoneStand077PhoneBase1Config
from .robotwin_place_phone_stand_077_phone_base2.config import TaskConfig as RobotwinPlacePhoneStand077PhoneBase2Config
from .robotwin_place_phone_stand_077_phone_base3.config import TaskConfig as RobotwinPlacePhoneStand077PhoneBase3Config
from .robotwin_place_phone_stand_077_phone_base4.config import TaskConfig as RobotwinPlacePhoneStand077PhoneBase4Config
from .robotwin_place_phone_stand_078_phonestand_base0.config import TaskConfig as RobotwinPlacePhoneStand078PhonestandBase0Config
from .robotwin_place_phone_stand_078_phonestand_base1.config import TaskConfig as RobotwinPlacePhoneStand078PhonestandBase1Config
from .robotwin_place_phone_stand_078_phonestand_base2.config import TaskConfig as RobotwinPlacePhoneStand078PhonestandBase2Config
from .robotwin_place_shoe_041_shoe_base0.config import TaskConfig as RobotwinPlaceShoe041ShoeBase0Config
from .robotwin_place_shoe_041_shoe_base2.config import TaskConfig as RobotwinPlaceShoe041ShoeBase2Config
from .robotwin_place_shoe_041_shoe_base4.config import TaskConfig as RobotwinPlaceShoe041ShoeBase4Config
from .robotwin_press_stapler_048_stapler_base0.config import TaskConfig as RobotwinPressStapler048StaplerBase0Config
from .robotwin_press_stapler_048_stapler_base1.config import TaskConfig as RobotwinPressStapler048StaplerBase1Config
from .robotwin_press_stapler_048_stapler_base2.config import TaskConfig as RobotwinPressStapler048StaplerBase2Config
from .robotwin_press_stapler_048_stapler_base3.config import TaskConfig as RobotwinPressStapler048StaplerBase3Config
from .robotwin_press_stapler_048_stapler_base4.config import TaskConfig as RobotwinPressStapler048StaplerBase4Config
from .robotwin_press_stapler_048_stapler_base5.config import TaskConfig as RobotwinPressStapler048StaplerBase5Config
from .robotwin_press_stapler_048_stapler_base6.config import TaskConfig as RobotwinPressStapler048StaplerBase6Config
from .robotwin_put_bottles_dustbin_011_dustbin.config import TaskConfig as RobotwinPutBottlesDustbin011DustbinConfig
from .robotwin_put_bottles_dustbin_011_dustbin_base0.config import TaskConfig as RobotwinPutBottlesDustbin011DustbinBase0Config
from .robotwin_put_bottles_dustbin_114_bottle_base1.config import TaskConfig as RobotwinPutBottlesDustbin114BottleBase1Config
from .robotwin_put_bottles_dustbin_114_bottle_base2.config import TaskConfig as RobotwinPutBottlesDustbin114BottleBase2Config
from .robotwin_put_bottles_dustbin_114_bottle_base3.config import TaskConfig as RobotwinPutBottlesDustbin114BottleBase3Config
from .robotwin_put_bottles_dustbin_114_bottle_base4.config import TaskConfig as RobotwinPutBottlesDustbin114BottleBase4Config
from .robotwin_put_object_cabinet_047_mouse_base0.config import TaskConfig as RobotwinPutObjectCabinet047MouseBase0Config
from .robotwin_put_object_cabinet_047_mouse_base1.config import TaskConfig as RobotwinPutObjectCabinet047MouseBase1Config
from .robotwin_put_object_cabinet_047_mouse_base2.config import TaskConfig as RobotwinPutObjectCabinet047MouseBase2Config
from .robotwin_put_object_cabinet_048_stapler_base0.config import TaskConfig as RobotwinPutObjectCabinet048StaplerBase0Config
from .robotwin_put_object_cabinet_048_stapler_base1.config import TaskConfig as RobotwinPutObjectCabinet048StaplerBase1Config
from .robotwin_put_object_cabinet_048_stapler_base2.config import TaskConfig as RobotwinPutObjectCabinet048StaplerBase2Config
from .robotwin_put_object_cabinet_048_stapler_base3.config import TaskConfig as RobotwinPutObjectCabinet048StaplerBase3Config
from .robotwin_put_object_cabinet_048_stapler_base4.config import TaskConfig as RobotwinPutObjectCabinet048StaplerBase4Config
from .robotwin_scan_object_024_scanner.config import TaskConfig as RobotwinScanObject024ScannerConfig
from .robotwin_scan_object_024_scanner_base2.config import TaskConfig as RobotwinScanObject024ScannerBase2Config
from .robotwin_scan_object_112_tea_box_base0.config import TaskConfig as RobotwinScanObject112TeaBoxBase0Config
from .robotwin_scan_object_112_tea_box_base3.config import TaskConfig as RobotwinScanObject112TeaBoxBase3Config
from .robotwin_scan_object_112_tea_box_base4.config import TaskConfig as RobotwinScanObject112TeaBoxBase4Config
from .robotwin_scan_object_112_tea_box_base5.config import TaskConfig as RobotwinScanObject112TeaBoxBase5Config
from .robotwin_shake_bottle_001_bottle.config import TaskConfig as RobotwinShakeBottle001BottleConfig
from .robotwin_shake_bottle_001_bottle_base0.config import TaskConfig as RobotwinShakeBottle001BottleBase0Config
from .robotwin_shake_bottle_001_bottle_base10.config import TaskConfig as RobotwinShakeBottle001BottleBase10Config
from .robotwin_shake_bottle_001_bottle_base11.config import TaskConfig as RobotwinShakeBottle001BottleBase11Config
from .robotwin_shake_bottle_001_bottle_base13.config import TaskConfig as RobotwinShakeBottle001BottleBase13Config
from .robotwin_shake_bottle_horizontally_001_bottle.config import TaskConfig as RobotwinShakeBottleHorizontally001BottleConfig
from .robotwin_shake_bottle_horizontally_001_bottle_base0.config import TaskConfig as RobotwinShakeBottleHorizontally001BottleBase0Config
from .robotwin_shake_bottle_horizontally_001_bottle_base10.config import TaskConfig as RobotwinShakeBottleHorizontally001BottleBase10Config
from .robotwin_shake_bottle_horizontally_001_bottle_base11.config import TaskConfig as RobotwinShakeBottleHorizontally001BottleBase11Config
from .robotwin_shake_bottle_horizontally_001_bottle_base13.config import TaskConfig as RobotwinShakeBottleHorizontally001BottleBase13Config
from .robotwin_stack_blocks_three_box_demo.config import TaskConfig as RobotwinStackBlocksThreeBoxDemoConfig
from .robotwin_stack_blocks_two_box_demo.config import TaskConfig as RobotwinStackBlocksTwoBoxDemoConfig
from .robotwin_stack_bowls_three_002_bowl.config import TaskConfig as RobotwinStackBowlsThree002BowlConfig
from .robotwin_stack_bowls_three_002_bowl_base1.config import TaskConfig as RobotwinStackBowlsThree002BowlBase1Config
from .robotwin_stack_bowls_three_002_bowl_base2.config import TaskConfig as RobotwinStackBowlsThree002BowlBase2Config
from .robotwin_stack_bowls_three_002_bowl_base3.config import TaskConfig as RobotwinStackBowlsThree002BowlBase3Config
from .robotwin_stack_bowls_three_002_bowl_base4.config import TaskConfig as RobotwinStackBowlsThree002BowlBase4Config
from .robotwin_stack_bowls_three_002_bowl_base5.config import TaskConfig as RobotwinStackBowlsThree002BowlBase5Config
from .robotwin_stack_bowls_three_002_bowl_base6.config import TaskConfig as RobotwinStackBowlsThree002BowlBase6Config
from .robotwin_stack_bowls_three_002_bowl_base7.config import TaskConfig as RobotwinStackBowlsThree002BowlBase7Config
from .robotwin_stack_bowls_two_002_bowl.config import TaskConfig as RobotwinStackBowlsTwo002BowlConfig
from .robotwin_stack_bowls_two_002_bowl_base1.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase1Config
from .robotwin_stack_bowls_two_002_bowl_base2.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase2Config
from .robotwin_stack_bowls_two_002_bowl_base3.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase3Config
from .robotwin_stack_bowls_two_002_bowl_base4.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase4Config
from .robotwin_stack_bowls_two_002_bowl_base5.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase5Config
from .robotwin_stack_bowls_two_002_bowl_base6.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase6Config
from .robotwin_stack_bowls_two_002_bowl_base7.config import TaskConfig as RobotwinStackBowlsTwo002BowlBase7Config
from .robotwin_stamp_seal_100_seal_base1.config import TaskConfig as RobotwinStampSeal100SealBase1Config
from .robotwin_stamp_seal_100_seal_base2.config import TaskConfig as RobotwinStampSeal100SealBase2Config
from .robotwin_stamp_seal_100_seal_base3.config import TaskConfig as RobotwinStampSeal100SealBase3Config
from .robotwin_stamp_seal_100_seal_base4.config import TaskConfig as RobotwinStampSeal100SealBase4Config
from .robotwin_stamp_seal_100_seal_base6.config import TaskConfig as RobotwinStampSeal100SealBase6Config

ROBOTWIN_CONFIG_MAPPING = {
    "robotwin_adjust_bottle_001_bottle": RobotwinAdjustBottle001BottleConfig,
    "robotwin_adjust_bottle_001_bottle_base0": RobotwinAdjustBottle001BottleBase0Config,
    "robotwin_adjust_bottle_001_bottle_base10": RobotwinAdjustBottle001BottleBase10Config,
    "robotwin_adjust_bottle_001_bottle_base11": RobotwinAdjustBottle001BottleBase11Config,
    "robotwin_adjust_bottle_001_bottle_base13": RobotwinAdjustBottle001BottleBase13Config,
    "robotwin_beat_block_hammer_020_hammer": RobotwinBeatBlockHammer020HammerConfig,
    "robotwin_blocks_ranking_rgb_box_demo": RobotwinBlocksRankingRgbBoxDemoConfig,
    "robotwin_blocks_ranking_size_box_demo": RobotwinBlocksRankingSizeBoxDemoConfig,
    "robotwin_click_alarmclock_046_alarm_clock_base1": RobotwinClickAlarmclock046AlarmClockBase1Config,
    "robotwin_click_alarmclock_046_alarm_clock_base2": RobotwinClickAlarmclock046AlarmClockBase2Config,
    "robotwin_click_alarmclock_046_alarm_clock_base3": RobotwinClickAlarmclock046AlarmClockBase3Config,
    "robotwin_click_alarmclock_046_alarm_clock_base4": RobotwinClickAlarmclock046AlarmClockBase4Config,
    "robotwin_click_bell_050_bell_base0": RobotwinClickBell050BellBase0Config,
    "robotwin_click_bell_050_bell_base1": RobotwinClickBell050BellBase1Config,
    "robotwin_dump_bin_bigbin_011_dustbin": RobotwinDumpBinBigbin011DustbinConfig,
    "robotwin_dump_bin_bigbin_011_dustbin_base0": RobotwinDumpBinBigbin011DustbinBase0Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base0": RobotwinDumpBinBigbin063TabletrashbinBase0Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base1": RobotwinDumpBinBigbin063TabletrashbinBase1Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base10": RobotwinDumpBinBigbin063TabletrashbinBase10Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base2": RobotwinDumpBinBigbin063TabletrashbinBase2Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base3": RobotwinDumpBinBigbin063TabletrashbinBase3Config,
    "robotwin_dump_bin_bigbin_063_tabletrashbin_base4": RobotwinDumpBinBigbin063TabletrashbinBase4Config,
    "robotwin_grab_roller_102_roller_base1": RobotwinGrabRoller102RollerBase1Config,
    "robotwin_grab_roller_102_roller_base2": RobotwinGrabRoller102RollerBase2Config,
    "robotwin_hanging_mug_039_mug_base0": RobotwinHangingMug039MugBase0Config,
    "robotwin_hanging_mug_039_mug_base1": RobotwinHangingMug039MugBase1Config,
    "robotwin_hanging_mug_039_mug_base10": RobotwinHangingMug039MugBase10Config,
    "robotwin_hanging_mug_039_mug_base11": RobotwinHangingMug039MugBase11Config,
    "robotwin_hanging_mug_039_mug_base12": RobotwinHangingMug039MugBase12Config,
    "robotwin_hanging_mug_039_mug_base2": RobotwinHangingMug039MugBase2Config,
    "robotwin_hanging_mug_039_mug_base3": RobotwinHangingMug039MugBase3Config,
    "robotwin_hanging_mug_039_mug_base4": RobotwinHangingMug039MugBase4Config,
    "robotwin_lift_pot_060_kitchenpot_base0": RobotwinLiftPot060KitchenpotBase0Config,
    "robotwin_lift_pot_060_kitchenpot_base1": RobotwinLiftPot060KitchenpotBase1Config,
    "robotwin_lift_pot_060_kitchenpot_base2": RobotwinLiftPot060KitchenpotBase2Config,
    "robotwin_lift_pot_060_kitchenpot_base3": RobotwinLiftPot060KitchenpotBase3Config,
    "robotwin_lift_pot_060_kitchenpot_base4": RobotwinLiftPot060KitchenpotBase4Config,
    "robotwin_lift_pot_060_kitchenpot_base5": RobotwinLiftPot060KitchenpotBase5Config,
    "robotwin_lift_pot_060_kitchenpot_base6": RobotwinLiftPot060KitchenpotBase6Config,
    "robotwin_lift_pot_060_kitchenpot_base7": RobotwinLiftPot060KitchenpotBase7Config,
    "robotwin_move_can_pot_060_kitchenpot_base0": RobotwinMoveCanPot060KitchenpotBase0Config,
    "robotwin_move_can_pot_060_kitchenpot_base1": RobotwinMoveCanPot060KitchenpotBase1Config,
    "robotwin_move_can_pot_060_kitchenpot_base2": RobotwinMoveCanPot060KitchenpotBase2Config,
    "robotwin_move_can_pot_060_kitchenpot_base3": RobotwinMoveCanPot060KitchenpotBase3Config,
    "robotwin_move_can_pot_060_kitchenpot_base4": RobotwinMoveCanPot060KitchenpotBase4Config,
    "robotwin_move_can_pot_060_kitchenpot_base5": RobotwinMoveCanPot060KitchenpotBase5Config,
    "robotwin_move_can_pot_060_kitchenpot_base6": RobotwinMoveCanPot060KitchenpotBase6Config,
    "robotwin_move_can_pot_060_kitchenpot_base7": RobotwinMoveCanPot060KitchenpotBase7Config,
    "robotwin_move_pillbottle_pad_080_pillbottle_base1": RobotwinMovePillbottlePad080PillbottleBase1Config,
    "robotwin_move_pillbottle_pad_080_pillbottle_base4": RobotwinMovePillbottlePad080PillbottleBase4Config,
    "robotwin_move_pillbottle_pad_080_pillbottle_base5": RobotwinMovePillbottlePad080PillbottleBase5Config,
    "robotwin_move_playingcard_away_081_playingcards_base0": RobotwinMovePlayingcardAway081PlayingcardsBase0Config,
    "robotwin_move_playingcard_away_081_playingcards_base1": RobotwinMovePlayingcardAway081PlayingcardsBase1Config,
    "robotwin_move_playingcard_away_081_playingcards_base2": RobotwinMovePlayingcardAway081PlayingcardsBase2Config,
    "robotwin_move_stapler_pad_048_stapler_base0": RobotwinMoveStaplerPad048StaplerBase0Config,
    "robotwin_move_stapler_pad_048_stapler_base1": RobotwinMoveStaplerPad048StaplerBase1Config,
    "robotwin_move_stapler_pad_048_stapler_base2": RobotwinMoveStaplerPad048StaplerBase2Config,
    "robotwin_move_stapler_pad_048_stapler_base3": RobotwinMoveStaplerPad048StaplerBase3Config,
    "robotwin_move_stapler_pad_048_stapler_base4": RobotwinMoveStaplerPad048StaplerBase4Config,
    "robotwin_move_stapler_pad_048_stapler_base5": RobotwinMoveStaplerPad048StaplerBase5Config,
    "robotwin_move_stapler_pad_048_stapler_base6": RobotwinMoveStaplerPad048StaplerBase6Config,
    "robotwin_pick_diverse_bottles_001_bottle": RobotwinPickDiverseBottles001BottleConfig,
    "robotwin_pick_diverse_bottles_001_bottle_base0": RobotwinPickDiverseBottles001BottleBase0Config,
    "robotwin_pick_diverse_bottles_001_bottle_base10": RobotwinPickDiverseBottles001BottleBase10Config,
    "robotwin_pick_diverse_bottles_001_bottle_base11": RobotwinPickDiverseBottles001BottleBase11Config,
    "robotwin_pick_diverse_bottles_001_bottle_base13": RobotwinPickDiverseBottles001BottleBase13Config,
    "robotwin_pick_dual_bottles_001_bottle": RobotwinPickDualBottles001BottleConfig,
    "robotwin_pick_dual_bottles_001_bottle_base0": RobotwinPickDualBottles001BottleBase0Config,
    "robotwin_pick_dual_bottles_001_bottle_base10": RobotwinPickDualBottles001BottleBase10Config,
    "robotwin_pick_dual_bottles_001_bottle_base11": RobotwinPickDualBottles001BottleBase11Config,
    "robotwin_pick_dual_bottles_001_bottle_base13": RobotwinPickDualBottles001BottleBase13Config,
    "robotwin_place_a2b_left_047_mouse_base0": RobotwinPlaceA2bLeft047MouseBase0Config,
    "robotwin_place_a2b_left_047_mouse_base1": RobotwinPlaceA2bLeft047MouseBase1Config,
    "robotwin_place_a2b_left_047_mouse_base2": RobotwinPlaceA2bLeft047MouseBase2Config,
    "robotwin_place_a2b_left_048_stapler_base0": RobotwinPlaceA2bLeft048StaplerBase0Config,
    "robotwin_place_a2b_left_048_stapler_base1": RobotwinPlaceA2bLeft048StaplerBase1Config,
    "robotwin_place_a2b_left_048_stapler_base2": RobotwinPlaceA2bLeft048StaplerBase2Config,
    "robotwin_place_a2b_left_048_stapler_base3": RobotwinPlaceA2bLeft048StaplerBase3Config,
    "robotwin_place_a2b_left_048_stapler_base4": RobotwinPlaceA2bLeft048StaplerBase4Config,
    "robotwin_place_a2b_right_047_mouse_base0": RobotwinPlaceA2bRight047MouseBase0Config,
    "robotwin_place_a2b_right_047_mouse_base1": RobotwinPlaceA2bRight047MouseBase1Config,
    "robotwin_place_a2b_right_047_mouse_base2": RobotwinPlaceA2bRight047MouseBase2Config,
    "robotwin_place_a2b_right_048_stapler_base0": RobotwinPlaceA2bRight048StaplerBase0Config,
    "robotwin_place_a2b_right_048_stapler_base1": RobotwinPlaceA2bRight048StaplerBase1Config,
    "robotwin_place_a2b_right_048_stapler_base2": RobotwinPlaceA2bRight048StaplerBase2Config,
    "robotwin_place_a2b_right_048_stapler_base3": RobotwinPlaceA2bRight048StaplerBase3Config,
    "robotwin_place_a2b_right_048_stapler_base4": RobotwinPlaceA2bRight048StaplerBase4Config,
    "robotwin_place_bread_basket_075_bread_base0": RobotwinPlaceBreadBasket075BreadBase0Config,
    "robotwin_place_bread_basket_075_bread_base1": RobotwinPlaceBreadBasket075BreadBase1Config,
    "robotwin_place_bread_basket_075_bread_base2": RobotwinPlaceBreadBasket075BreadBase2Config,
    "robotwin_place_bread_basket_076_breadbasket_base0": RobotwinPlaceBreadBasket076BreadbasketBase0Config,
    "robotwin_place_bread_basket_076_breadbasket_base1": RobotwinPlaceBreadBasket076BreadbasketBase1Config,
    "robotwin_place_bread_basket_076_breadbasket_base2": RobotwinPlaceBreadBasket076BreadbasketBase2Config,
    "robotwin_place_bread_basket_076_breadbasket_base3": RobotwinPlaceBreadBasket076BreadbasketBase3Config,
    "robotwin_place_bread_basket_076_breadbasket_base4": RobotwinPlaceBreadBasket076BreadbasketBase4Config,
    "robotwin_place_bread_skillet_075_bread_base0": RobotwinPlaceBreadSkillet075BreadBase0Config,
    "robotwin_place_bread_skillet_075_bread_base1": RobotwinPlaceBreadSkillet075BreadBase1Config,
    "robotwin_place_bread_skillet_075_bread_base2": RobotwinPlaceBreadSkillet075BreadBase2Config,
    "robotwin_place_bread_skillet_075_bread_base3": RobotwinPlaceBreadSkillet075BreadBase3Config,
    "robotwin_place_bread_skillet_075_bread_base4": RobotwinPlaceBreadSkillet075BreadBase4Config,
    "robotwin_place_bread_skillet_075_bread_base5": RobotwinPlaceBreadSkillet075BreadBase5Config,
    "robotwin_place_bread_skillet_075_bread_base6": RobotwinPlaceBreadSkillet075BreadBase6Config,
    "robotwin_place_bread_skillet_106_skillet_base0": RobotwinPlaceBreadSkillet106SkilletBase0Config,
    "robotwin_place_burger_fries_006_hamburg": RobotwinPlaceBurgerFries006HamburgConfig,
    "robotwin_place_burger_fries_006_hamburg_base0": RobotwinPlaceBurgerFries006HamburgBase0Config,
    "robotwin_place_burger_fries_006_hamburg_base1": RobotwinPlaceBurgerFries006HamburgBase1Config,
    "robotwin_place_burger_fries_008_tray": RobotwinPlaceBurgerFries008TrayConfig,
    "robotwin_place_burger_fries_008_tray_base0": RobotwinPlaceBurgerFries008TrayBase0Config,
    "robotwin_place_burger_fries_008_tray_base1": RobotwinPlaceBurgerFries008TrayBase1Config,
    "robotwin_place_burger_fries_008_tray_base2": RobotwinPlaceBurgerFries008TrayBase2Config,
    "robotwin_place_burger_fries_008_tray_base3": RobotwinPlaceBurgerFries008TrayBase3Config,
    "robotwin_place_can_basket_071_can_base0": RobotwinPlaceCanBasket071CanBase0Config,
    "robotwin_place_can_basket_071_can_base1": RobotwinPlaceCanBasket071CanBase1Config,
    "robotwin_place_can_basket_071_can_base2": RobotwinPlaceCanBasket071CanBase2Config,
    "robotwin_place_can_basket_071_can_base3": RobotwinPlaceCanBasket071CanBase3Config,
    "robotwin_place_can_basket_110_basket_base0": RobotwinPlaceCanBasket110BasketBase0Config,
    "robotwin_place_can_basket_110_basket_base1": RobotwinPlaceCanBasket110BasketBase1Config,
    "robotwin_place_can_basket_110_basket_base2": RobotwinPlaceCanBasket110BasketBase2Config,
    "robotwin_place_can_basket_110_basket_base3": RobotwinPlaceCanBasket110BasketBase3Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base0": RobotwinPlaceCansPlasticbox062PlasticboxBase0Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base1": RobotwinPlaceCansPlasticbox062PlasticboxBase1Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base10": RobotwinPlaceCansPlasticbox062PlasticboxBase10Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base2": RobotwinPlaceCansPlasticbox062PlasticboxBase2Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base3": RobotwinPlaceCansPlasticbox062PlasticboxBase3Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base4": RobotwinPlaceCansPlasticbox062PlasticboxBase4Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base5": RobotwinPlaceCansPlasticbox062PlasticboxBase5Config,
    "robotwin_place_cans_plasticbox_062_plasticbox_base6": RobotwinPlaceCansPlasticbox062PlasticboxBase6Config,
    "robotwin_place_container_plate_002_bowl": RobotwinPlaceContainerPlate002BowlConfig,
    "robotwin_place_container_plate_002_bowl_base1": RobotwinPlaceContainerPlate002BowlBase1Config,
    "robotwin_place_container_plate_002_bowl_base2": RobotwinPlaceContainerPlate002BowlBase2Config,
    "robotwin_place_container_plate_002_bowl_base3": RobotwinPlaceContainerPlate002BowlBase3Config,
    "robotwin_place_container_plate_002_bowl_base4": RobotwinPlaceContainerPlate002BowlBase4Config,
    "robotwin_place_container_plate_002_bowl_base5": RobotwinPlaceContainerPlate002BowlBase5Config,
    "robotwin_place_container_plate_002_bowl_base6": RobotwinPlaceContainerPlate002BowlBase6Config,
    "robotwin_place_container_plate_002_bowl_base7": RobotwinPlaceContainerPlate002BowlBase7Config,
    "robotwin_place_dual_shoes_007_shoe_box": RobotwinPlaceDualShoes007ShoeBoxConfig,
    "robotwin_place_dual_shoes_007_shoe_box_base0": RobotwinPlaceDualShoes007ShoeBoxBase0Config,
    "robotwin_place_dual_shoes_041_shoe_base0": RobotwinPlaceDualShoes041ShoeBase0Config,
    "robotwin_place_dual_shoes_041_shoe_base2": RobotwinPlaceDualShoes041ShoeBase2Config,
    "robotwin_place_dual_shoes_041_shoe_base4": RobotwinPlaceDualShoes041ShoeBase4Config,
    "robotwin_place_empty_cup_021_cup": RobotwinPlaceEmptyCup021CupConfig,
    "robotwin_place_empty_cup_021_cup_base0": RobotwinPlaceEmptyCup021CupBase0Config,
    "robotwin_place_empty_cup_021_cup_base1": RobotwinPlaceEmptyCup021CupBase1Config,
    "robotwin_place_empty_cup_021_cup_base10": RobotwinPlaceEmptyCup021CupBase10Config,
    "robotwin_place_empty_cup_021_cup_base11": RobotwinPlaceEmptyCup021CupBase11Config,
    "robotwin_place_empty_cup_021_cup_base12": RobotwinPlaceEmptyCup021CupBase12Config,
    "robotwin_place_empty_cup_021_cup_base2": RobotwinPlaceEmptyCup021CupBase2Config,
    "robotwin_place_empty_cup_021_cup_base3": RobotwinPlaceEmptyCup021CupBase3Config,
    "robotwin_place_fan_box_demo": RobotwinPlaceFanBoxDemoConfig,
    "robotwin_place_mouse_pad_047_mouse_base0": RobotwinPlaceMousePad047MouseBase0Config,
    "robotwin_place_mouse_pad_047_mouse_base1": RobotwinPlaceMousePad047MouseBase1Config,
    "robotwin_place_mouse_pad_047_mouse_base2": RobotwinPlaceMousePad047MouseBase2Config,
    "robotwin_place_object_basket_057_toycar_base0": RobotwinPlaceObjectBasket057ToycarBase0Config,
    "robotwin_place_object_basket_057_toycar_base1": RobotwinPlaceObjectBasket057ToycarBase1Config,
    "robotwin_place_object_basket_057_toycar_base2": RobotwinPlaceObjectBasket057ToycarBase2Config,
    "robotwin_place_object_basket_057_toycar_base3": RobotwinPlaceObjectBasket057ToycarBase3Config,
    "robotwin_place_object_basket_110_basket_base0": RobotwinPlaceObjectBasket110BasketBase0Config,
    "robotwin_place_object_basket_110_basket_base1": RobotwinPlaceObjectBasket110BasketBase1Config,
    "robotwin_place_object_basket_110_basket_base2": RobotwinPlaceObjectBasket110BasketBase2Config,
    "robotwin_place_object_basket_110_basket_base3": RobotwinPlaceObjectBasket110BasketBase3Config,
    "robotwin_place_object_scale_047_mouse_base0": RobotwinPlaceObjectScale047MouseBase0Config,
    "robotwin_place_object_scale_047_mouse_base1": RobotwinPlaceObjectScale047MouseBase1Config,
    "robotwin_place_object_scale_047_mouse_base2": RobotwinPlaceObjectScale047MouseBase2Config,
    "robotwin_place_object_scale_048_stapler_base0": RobotwinPlaceObjectScale048StaplerBase0Config,
    "robotwin_place_object_scale_048_stapler_base1": RobotwinPlaceObjectScale048StaplerBase1Config,
    "robotwin_place_object_scale_048_stapler_base2": RobotwinPlaceObjectScale048StaplerBase2Config,
    "robotwin_place_object_scale_048_stapler_base3": RobotwinPlaceObjectScale048StaplerBase3Config,
    "robotwin_place_object_scale_048_stapler_base4": RobotwinPlaceObjectScale048StaplerBase4Config,
    "robotwin_place_object_stand_047_mouse_base0": RobotwinPlaceObjectStand047MouseBase0Config,
    "robotwin_place_object_stand_047_mouse_base1": RobotwinPlaceObjectStand047MouseBase1Config,
    "robotwin_place_object_stand_047_mouse_base2": RobotwinPlaceObjectStand047MouseBase2Config,
    "robotwin_place_object_stand_048_stapler_base0": RobotwinPlaceObjectStand048StaplerBase0Config,
    "robotwin_place_object_stand_048_stapler_base1": RobotwinPlaceObjectStand048StaplerBase1Config,
    "robotwin_place_object_stand_048_stapler_base2": RobotwinPlaceObjectStand048StaplerBase2Config,
    "robotwin_place_object_stand_048_stapler_base3": RobotwinPlaceObjectStand048StaplerBase3Config,
    "robotwin_place_object_stand_048_stapler_base4": RobotwinPlaceObjectStand048StaplerBase4Config,
    "robotwin_place_phone_stand_077_phone_base0": RobotwinPlacePhoneStand077PhoneBase0Config,
    "robotwin_place_phone_stand_077_phone_base1": RobotwinPlacePhoneStand077PhoneBase1Config,
    "robotwin_place_phone_stand_077_phone_base2": RobotwinPlacePhoneStand077PhoneBase2Config,
    "robotwin_place_phone_stand_077_phone_base3": RobotwinPlacePhoneStand077PhoneBase3Config,
    "robotwin_place_phone_stand_077_phone_base4": RobotwinPlacePhoneStand077PhoneBase4Config,
    "robotwin_place_phone_stand_078_phonestand_base0": RobotwinPlacePhoneStand078PhonestandBase0Config,
    "robotwin_place_phone_stand_078_phonestand_base1": RobotwinPlacePhoneStand078PhonestandBase1Config,
    "robotwin_place_phone_stand_078_phonestand_base2": RobotwinPlacePhoneStand078PhonestandBase2Config,
    "robotwin_place_shoe_041_shoe_base0": RobotwinPlaceShoe041ShoeBase0Config,
    "robotwin_place_shoe_041_shoe_base2": RobotwinPlaceShoe041ShoeBase2Config,
    "robotwin_place_shoe_041_shoe_base4": RobotwinPlaceShoe041ShoeBase4Config,
    "robotwin_press_stapler_048_stapler_base0": RobotwinPressStapler048StaplerBase0Config,
    "robotwin_press_stapler_048_stapler_base1": RobotwinPressStapler048StaplerBase1Config,
    "robotwin_press_stapler_048_stapler_base2": RobotwinPressStapler048StaplerBase2Config,
    "robotwin_press_stapler_048_stapler_base3": RobotwinPressStapler048StaplerBase3Config,
    "robotwin_press_stapler_048_stapler_base4": RobotwinPressStapler048StaplerBase4Config,
    "robotwin_press_stapler_048_stapler_base5": RobotwinPressStapler048StaplerBase5Config,
    "robotwin_press_stapler_048_stapler_base6": RobotwinPressStapler048StaplerBase6Config,
    "robotwin_put_bottles_dustbin_011_dustbin": RobotwinPutBottlesDustbin011DustbinConfig,
    "robotwin_put_bottles_dustbin_011_dustbin_base0": RobotwinPutBottlesDustbin011DustbinBase0Config,
    "robotwin_put_bottles_dustbin_114_bottle_base1": RobotwinPutBottlesDustbin114BottleBase1Config,
    "robotwin_put_bottles_dustbin_114_bottle_base2": RobotwinPutBottlesDustbin114BottleBase2Config,
    "robotwin_put_bottles_dustbin_114_bottle_base3": RobotwinPutBottlesDustbin114BottleBase3Config,
    "robotwin_put_bottles_dustbin_114_bottle_base4": RobotwinPutBottlesDustbin114BottleBase4Config,
    "robotwin_put_object_cabinet_047_mouse_base0": RobotwinPutObjectCabinet047MouseBase0Config,
    "robotwin_put_object_cabinet_047_mouse_base1": RobotwinPutObjectCabinet047MouseBase1Config,
    "robotwin_put_object_cabinet_047_mouse_base2": RobotwinPutObjectCabinet047MouseBase2Config,
    "robotwin_put_object_cabinet_048_stapler_base0": RobotwinPutObjectCabinet048StaplerBase0Config,
    "robotwin_put_object_cabinet_048_stapler_base1": RobotwinPutObjectCabinet048StaplerBase1Config,
    "robotwin_put_object_cabinet_048_stapler_base2": RobotwinPutObjectCabinet048StaplerBase2Config,
    "robotwin_put_object_cabinet_048_stapler_base3": RobotwinPutObjectCabinet048StaplerBase3Config,
    "robotwin_put_object_cabinet_048_stapler_base4": RobotwinPutObjectCabinet048StaplerBase4Config,
    "robotwin_scan_object_024_scanner": RobotwinScanObject024ScannerConfig,
    "robotwin_scan_object_024_scanner_base2": RobotwinScanObject024ScannerBase2Config,
    "robotwin_scan_object_112_tea_box_base0": RobotwinScanObject112TeaBoxBase0Config,
    "robotwin_scan_object_112_tea_box_base3": RobotwinScanObject112TeaBoxBase3Config,
    "robotwin_scan_object_112_tea_box_base4": RobotwinScanObject112TeaBoxBase4Config,
    "robotwin_scan_object_112_tea_box_base5": RobotwinScanObject112TeaBoxBase5Config,
    "robotwin_shake_bottle_001_bottle": RobotwinShakeBottle001BottleConfig,
    "robotwin_shake_bottle_001_bottle_base0": RobotwinShakeBottle001BottleBase0Config,
    "robotwin_shake_bottle_001_bottle_base10": RobotwinShakeBottle001BottleBase10Config,
    "robotwin_shake_bottle_001_bottle_base11": RobotwinShakeBottle001BottleBase11Config,
    "robotwin_shake_bottle_001_bottle_base13": RobotwinShakeBottle001BottleBase13Config,
    "robotwin_shake_bottle_horizontally_001_bottle": RobotwinShakeBottleHorizontally001BottleConfig,
    "robotwin_shake_bottle_horizontally_001_bottle_base0": RobotwinShakeBottleHorizontally001BottleBase0Config,
    "robotwin_shake_bottle_horizontally_001_bottle_base10": RobotwinShakeBottleHorizontally001BottleBase10Config,
    "robotwin_shake_bottle_horizontally_001_bottle_base11": RobotwinShakeBottleHorizontally001BottleBase11Config,
    "robotwin_shake_bottle_horizontally_001_bottle_base13": RobotwinShakeBottleHorizontally001BottleBase13Config,
    "robotwin_stack_blocks_three_box_demo": RobotwinStackBlocksThreeBoxDemoConfig,
    "robotwin_stack_blocks_two_box_demo": RobotwinStackBlocksTwoBoxDemoConfig,
    "robotwin_stack_bowls_three_002_bowl": RobotwinStackBowlsThree002BowlConfig,
    "robotwin_stack_bowls_three_002_bowl_base1": RobotwinStackBowlsThree002BowlBase1Config,
    "robotwin_stack_bowls_three_002_bowl_base2": RobotwinStackBowlsThree002BowlBase2Config,
    "robotwin_stack_bowls_three_002_bowl_base3": RobotwinStackBowlsThree002BowlBase3Config,
    "robotwin_stack_bowls_three_002_bowl_base4": RobotwinStackBowlsThree002BowlBase4Config,
    "robotwin_stack_bowls_three_002_bowl_base5": RobotwinStackBowlsThree002BowlBase5Config,
    "robotwin_stack_bowls_three_002_bowl_base6": RobotwinStackBowlsThree002BowlBase6Config,
    "robotwin_stack_bowls_three_002_bowl_base7": RobotwinStackBowlsThree002BowlBase7Config,
    "robotwin_stack_bowls_two_002_bowl": RobotwinStackBowlsTwo002BowlConfig,
    "robotwin_stack_bowls_two_002_bowl_base1": RobotwinStackBowlsTwo002BowlBase1Config,
    "robotwin_stack_bowls_two_002_bowl_base2": RobotwinStackBowlsTwo002BowlBase2Config,
    "robotwin_stack_bowls_two_002_bowl_base3": RobotwinStackBowlsTwo002BowlBase3Config,
    "robotwin_stack_bowls_two_002_bowl_base4": RobotwinStackBowlsTwo002BowlBase4Config,
    "robotwin_stack_bowls_two_002_bowl_base5": RobotwinStackBowlsTwo002BowlBase5Config,
    "robotwin_stack_bowls_two_002_bowl_base6": RobotwinStackBowlsTwo002BowlBase6Config,
    "robotwin_stack_bowls_two_002_bowl_base7": RobotwinStackBowlsTwo002BowlBase7Config,
    "robotwin_stamp_seal_100_seal_base1": RobotwinStampSeal100SealBase1Config,
    "robotwin_stamp_seal_100_seal_base2": RobotwinStampSeal100SealBase2Config,
    "robotwin_stamp_seal_100_seal_base3": RobotwinStampSeal100SealBase3Config,
    "robotwin_stamp_seal_100_seal_base4": RobotwinStampSeal100SealBase4Config,
    "robotwin_stamp_seal_100_seal_base6": RobotwinStampSeal100SealBase6Config,
}
